<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.01-10 -->
<!--                                          -->
<!-- Copyright 1997-2000 Bradford L. Barrett  -->
<!-- (brad@mrunix.net  http://www.mrunix.net) -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--     http://www.mrunix.net/webalizer/     -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 06-Apr-2016 03:19 EDT *** -->

<HTML>
<HEAD>
 <TITLE>Website Statistics: magento2-demo.nexcess.net - Last 12 Months</TITLE>
</HEAD>

<BODY BGCOLOR="#E8E8E8" TEXT="#000000" LINK="#0000FF" VLINK="#FF0000">
<H2>Website Statistics: magento2-demo.nexcess.net</H2>
<SMALL><STRONG>
Summary Period: Last 12 Months<BR>
Generated 06-Apr-2016 03:19 EDT<BR>
</STRONG></SMALL>
<CENTER>
<HR>
<P>
<IMG SRC="stats.php?mode=webalizer&action=load&image=usage.png" ALT="Usage summary for magento2-demo.nexcess.net" HEIGHT=256 WIDTH=512><P>
<TABLE WIDTH=600 BORDER=2 CELLSPACING=1 CELLPADDING=1>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH COLSPAN=11 BGCOLOR="#c0c0c0" ALIGN=center>Summary by Month</TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH ALIGN=left ROWSPAN=2 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Month</FONT></TH>
<TH ALIGN=center COLSPAN=4 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Daily Avg</FONT></TH>
<TH ALIGN=center COLSPAN=6 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Monthly Totals</FONT></TH></TR>
<TR><TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff8000"><FONT SIZE="-1">Sites</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff0000"><FONT SIZE="-1">KBytes</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201604.php"><FONT SIZE="-1">Apr 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">2550</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2333</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1794</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">73</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">218</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">292190</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">365</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">8974</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">11665</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">12753</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201603.php"><FONT SIZE="-1">Mar 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">72609</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">66644</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">46532</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3020</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">5847</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">93361106</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">93627</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1442507</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2065981</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2250909</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201602.php"><FONT SIZE="-1">Feb 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">65050</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">60345</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">46261</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1766</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3807</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">95770144</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">51219</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1341589</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1750026</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1886474</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201601.php"><FONT SIZE="-1">Jan 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">84588</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">77444</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">53517</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1879</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">5958</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">109827156</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">58249</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1659043</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2400781</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2622257</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201512.php"><FONT SIZE="-1">Dec 2015</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">39768</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">33863</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">11985</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1002</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">5388</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">16908467</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">31084</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">371540</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1049759</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1232823</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201511.php"><FONT SIZE="-1">Nov 2015</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">60584</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">52291</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">15022</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1097</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2914</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">12204689</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">12073</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">165246</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">575206</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">666434</FONT></TD></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH BGCOLOR="#c0c0c0" COLSPAN=6 ALIGN=left><FONT SIZE="-1">Totals</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">328363752</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">246617</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">4988899</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">7853418</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">8671650</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
</TABLE>
</CENTER>
<P>
<HR>
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
</TR>
</TABLE>

<!-- Webalizer Version 2.01-10 (Mod: 16-Apr-2002) -->

</BODY>
</HTML>
