<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.01-10 -->
<!--                                          -->
<!-- Copyright 1997-2000 Bradford L. Barrett  -->
<!-- (brad@mrunix.net  http://www.mrunix.net) -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--     http://www.mrunix.net/webalizer/     -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 06-Apr-2016 03:19 EDT *** -->

<HTML>
<HEAD>
 <TITLE>Website Statistics: php7.magento2-demo.nexcess.net - Last 12 Months</TITLE>
</HEAD>

<BODY BGCOLOR="#E8E8E8" TEXT="#000000" LINK="#0000FF" VLINK="#FF0000">
<H2>Website Statistics: php7.magento2-demo.nexcess.net</H2>
<SMALL><STRONG>
Summary Period: Last 12 Months<BR>
Generated 06-Apr-2016 03:19 EDT<BR>
</STRONG></SMALL>
<CENTER>
<HR>
<P>
<IMG SRC="stats.php?mode=webalizer&action=load&image=usage.png" ALT="Usage summary for php7.magento2-demo.nexcess.net" HEIGHT=256 WIDTH=512><P>
<TABLE WIDTH=600 BORDER=2 CELLSPACING=1 CELLPADDING=1>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH COLSPAN=11 BGCOLOR="#c0c0c0" ALIGN=center>Summary by Month</TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH ALIGN=left ROWSPAN=2 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Month</FONT></TH>
<TH ALIGN=center COLSPAN=4 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Daily Avg</FONT></TH>
<TH ALIGN=center COLSPAN=6 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Monthly Totals</FONT></TH></TR>
<TR><TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff8000"><FONT SIZE="-1">Sites</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff0000"><FONT SIZE="-1">KBytes</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201604.php"><FONT SIZE="-1">Apr 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">242</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">228</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">142</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">20</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">21</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">14129</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">103</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">712</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1141</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1210</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201603.php"><FONT SIZE="-1">Mar 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">1675</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1596</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">979</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">104</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">351</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1451809</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3252</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">30369</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">49480</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">51942</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201602.php"><FONT SIZE="-1">Feb 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">10070</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">9940</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">9541</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">755</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">216</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">24336196</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">21895</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">276709</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">288267</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">292030</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201601.php"><FONT SIZE="-1">Jan 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">1763</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1472</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">484</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">40</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">338</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">527283</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1240</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">15014</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">45655</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">54659</FONT></TD></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201512.php"><FONT SIZE="-1">Dec 2015</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">7963</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">7068</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3568</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">464</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">322</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">2139052</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">5109</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">39248</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">77752</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">87595</FONT></TD></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH BGCOLOR="#c0c0c0" COLSPAN=6 ALIGN=left><FONT SIZE="-1">Totals</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">28468469</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">31599</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">362052</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">462295</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">487436</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
</TABLE>
</CENTER>
<P>
<HR>
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
</TR>
</TABLE>

<!-- Webalizer Version 2.01-10 (Mod: 16-Apr-2002) -->

</BODY>
</HTML>
