<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.01-10 -->
<!--                                          -->
<!-- Copyright 1997-2000 Bradford L. Barrett  -->
<!-- (brad@mrunix.net  http://www.mrunix.net) -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--     http://www.mrunix.net/webalizer/     -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 06-Jan-2016 03:19 EST *** -->

<HTML>
<HEAD>
 <TITLE>Website Statistics: test.magento2-demo.nexcess.net - Last 12 Months</TITLE>
</HEAD>

<BODY BGCOLOR="#E8E8E8" TEXT="#000000" LINK="#0000FF" VLINK="#FF0000">
<H2>Website Statistics: test.magento2-demo.nexcess.net</H2>
<SMALL><STRONG>
Summary Period: Last 12 Months<BR>
Generated 06-Jan-2016 03:19 EST<BR>
</STRONG></SMALL>
<CENTER>
<HR>
<P>
<IMG SRC="stats.php?mode=webalizer&action=load&image=usage.png" ALT="Usage summary for test.magento2-demo.nexcess.net" HEIGHT=256 WIDTH=512><P>
<TABLE WIDTH=600 BORDER=2 CELLSPACING=1 CELLPADDING=1>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH COLSPAN=11 BGCOLOR="#c0c0c0" ALIGN=center>Summary by Month</TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH ALIGN=left ROWSPAN=2 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Month</FONT></TH>
<TH ALIGN=center COLSPAN=4 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Daily Avg</FONT></TH>
<TH ALIGN=center COLSPAN=6 BGCOLOR="#c0c0c0"><FONT SIZE="-1">Monthly Totals</FONT></TH></TR>
<TR><TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff8000"><FONT SIZE="-1">Sites</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff0000"><FONT SIZE="-1">KBytes</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TD NOWRAP ><A HREF="stats.php?mode=webalizer&file=usage_201601.php"><FONT SIZE="-1">Jan 2016</FONT></A></TD>
<TD ALIGN=right ><FONT SIZE="-1">393</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">386</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">55</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">1</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">8102</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">3</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">55</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">386</FONT></TD>
<TD ALIGN=right ><FONT SIZE="-1">393</FONT></TD></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH BGCOLOR="#c0c0c0" COLSPAN=6 ALIGN=left><FONT SIZE="-1">Totals</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">8102</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">3</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">55</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">386</FONT></TH>
<TH BGCOLOR="#c0c0c0" ALIGN=right><FONT SIZE="-1">393</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
</TABLE>
</CENTER>
<P>
<HR>
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
</TR>
</TABLE>

<!-- Webalizer Version 2.01-10 (Mod: 16-Apr-2002) -->

</BODY>
</HTML>
